-- Custom auth seed example (no Supabase email signup required)
-- IMPORTANT: Replace hashes with values generated by bcrypt utility.

insert into public.profiles (id, role, name, is_active)
values
  ('11111111-1111-1111-1111-111111111111', 'teacher', '김선생', true),
  ('22222222-2222-2222-2222-222222222222', 'student', '이학생', true),
  ('33333333-3333-3333-3333-333333333333', 'student', '이학생', true),
  ('44444444-4444-4444-4444-444444444444', 'student', '박학생', true)
on conflict (id) do update
set
  role = excluded.role,
  name = excluded.name,
  is_active = excluded.is_active,
  updated_at = now();

insert into public.account_credentials (
  profile_id,
  role,
  teacher_login_id,
  password_hash,
  student_phone_last4_hash,
  is_active
)
values
  ('11111111-1111-1111-1111-111111111111', 'teacher', 'teacher01', '$2b$10$TODO_REPLACE_HASH', null, true),
  ('22222222-2222-2222-2222-222222222222', 'student', null, null, '$2b$10$TODO_REPLACE_HASH', true),
  ('33333333-3333-3333-3333-333333333333', 'student', null, null, '$2b$10$TODO_REPLACE_HASH', true),
  ('44444444-4444-4444-4444-444444444444', 'student', null, null, '$2b$10$TODO_REPLACE_HASH', true)
on conflict (profile_id) do update
set
  role = excluded.role,
  teacher_login_id = excluded.teacher_login_id,
  password_hash = excluded.password_hash,
  student_phone_last4_hash = excluded.student_phone_last4_hash,
  is_active = excluded.is_active,
  updated_at = now();

-- Example: if two students share same name and same last4 hash, login becomes ambiguous and fails safely.
